{{- TODO: Needs filter }}
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-cluster-node-tuning-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- /* Iterate through all PerformanceProfile objects for one that matches the intended role of this Tuned profile */}}
  {{- $profileName := "openshift-node-performance-profile" }}
  {{- $profiles := lookupCRs "performance.openshift.io/v2" "PerformanceProfile" "*" "*" }}
  {{- $matchingProfile := dict }}
  {{- /* Consider all 'recommend' sections in this Tuned profile */}}
    {{- range $r := .spec.recommend }}
      {{- range $profile := $profiles }}
        {{- $mclabels := $r.machineConfigLabels | default dict }}
        {{- $role := index $mclabels "machineconfiguration.openshift.io/role" }}
        {{- $selector := printf "pools.operator.machineconfiguration.openshift.io/%s" $role }}
        {{- $profileSelectors := $profile.spec.machineConfigPoolSelector | default dict }}
        {{- if hasKey $profileSelectors $selector }}
          {{- $matchingProfile = $profile }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- $powersaveSysfs := "" }}
  {{- if and (($matchingProfile.spec).workloadHints).perPodPowerManagement }}
    {{- if contains "max_perf_pct" (index .spec.profile 0).data }}
      {{- $powersaveSysfs = "[sysfs]\n/sys/devices/system/cpu/intel_pstate/max_perf_pct=(?<max_perf_pct>[0-9]+)" }}
    {{- end }}
  {{- end }}
  profile:
    - name: performance-patch
      # Please note:
      # - The 'include' line must match the associated PerformanceProfile name, following below pattern
      #   include=openshift-node-performance-${PerformanceProfile.metadata.name}
      # - When using the standard (non-realtime) kernel, remove the kernel.timer_migration override from
      #   the [sysctl] section and remove the entire section if it is empty.
      data: |
        [main]
        summary=Configuration changes profile inherited from performance created tuned
        include=openshift-node-performance-{{ $matchingProfile.metadata.name }}
        [scheduler]
        group.ice-ptp=0:f:10:*:ice-ptp.*
        group.ice-gnss=0:f:10:*:ice-gnss.*
        group.ice-dplls=0:f:10:*:ice-dplls.*
        [service]
        service.stalld=start,enable
        service.chronyd=stop,disable
        {{- if $powersaveSysfs }}
          {{- $powersaveSysfs | nindent 8 }}
        {{- end }}
  recommend:
  {{- range .spec.recommend }}
    - machineConfigLabels:
        {{- .machineConfigLabels | toYaml | nindent 8 }}
      priority: 19
      profile: performance-patch
  {{- end }}
